#!/usr/bin/env python3
"""Command-line interface for LinkedIn Ghostwriter."""

import sys
import os
from pathlib import Path

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from linkedin_ghostwriter import LinkedInGhostwriter, DashCountEvaluator, LLMJudgeEvaluator


def main():
    """Interactive command-line interface for LinkedIn Ghostwriter."""
    
    print("🚀 LinkedIn Ghostwriter - AI-powered post generation")
    print("=" * 50)
    
    try:
        # Initialize evaluators
        dash_evaluator = DashCountEvaluator()
        llm_evaluator = LLMJudgeEvaluator()
        
        # Create ghostwriter
        ghostwriter = LinkedInGhostwriter([dash_evaluator, llm_evaluator])
        
        print("✅ Ghostwriter initialized successfully!")
        print("\nEnter your raw notes (press Enter twice to finish):")
        
        # Collect raw notes
        lines = []
        while True:
            line = input()
            if line == "" and lines and lines[-1] == "":
                break
            lines.append(line)
        
        raw_notes = "\n".join(lines[:-1]).strip()  # Remove the last empty line
        
        if not raw_notes:
            print("❌ No notes provided. Exiting.")
            return
        
        print(f"\n📝 Processing notes: {raw_notes[:100]}{'...' if len(raw_notes) > 100 else ''}")
        print("\n🔄 Generating post with evaluation...")
        
        # Generate post
        final_post, iterations, passed = ghostwriter.generate_with_evaluation(raw_notes)
        
        print(f"\n📝 Generated Post (Iteration {iterations}):")
        print("-" * 50)
        print(final_post)
        print("-" * 50)
        
        if passed:
            print("✅ All evaluations passed!")
        else:
            print("⚠️ Some evaluations failed, but max iterations reached.")
        
        # Ask if user wants to save
        save = input("\n💾 Save this post to a file? (y/n): ").lower().strip()
        if save in ['y', 'yes']:
            filename = input("📁 Enter filename (default: linkedin_post.txt): ").strip()
            if not filename:
                filename = "linkedin_post.txt"
            
            with open(filename, 'w') as f:
                f.write(f"LinkedIn Post (Generated in {iterations} iterations)\n")
                f.write("=" * 50 + "\n\n")
                f.write(final_post)
                f.write(f"\n\n---\nGenerated by LinkedIn Ghostwriter\n")
            
            print(f"✅ Post saved to {filename}")
        
    except KeyboardInterrupt:
        print("\n\n👋 Goodbye!")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
